### ISSUE TITLE
Add Selection option

### ISSUE THREAD

**Issue by robisaks** [SythilTech/Odoo9#1]
It would be great if we could add dropdown type fields for crm_custom_fields

**Comment by SythilBlade** [comment]
Hi,
I've released v1.2 which has dropdown type fields.

**Comment by robisaks** [comment]
Where is the source for 1.2?

**Comment by robisaks** [comment]
Nevermind, I see you pushed it. Thanks!

**Comment by robisaks** [comment]
How do I get odoo to remove the cache of the older version? I've uninstalled it, restarted the service, delete the old version, and updated app list. But when I put the new version into the addons folder and refresh the ui, it still shows version 1.1.

**Comment by SythilBlade** [comment]
You may still have an old version in one of your add-on folders.
if you installed the module using the app store directly inside Odoo there might be a copy under
'/odoo/.local/share/Odoo/addons/9.0/' or wherever your .local folder is installed on your installation.
